rvm:
- 1.9.3
- 2.0.0
services:
- couchdb
env:
  global:
  - secure: RaH3aJBOSimWYeqImSGKbS85btmMjxoc45NoG+filEc1F/Lkg051ou1Bx5McybfC8orJlrR/YNLKX4+TuthcCfMjOkUbFru0dbf61lBTG6oh8MMFwNcxt7uJNZlENRJMp1k4XSZiNwSiPGW4LONSunTpbPs3mVqE8H8/rP7tUcM=
  - secure: ZbdrecyVUFR6GAS2XBjUQS1wrY0XmqAV9q1fkIBOjLlgrrWz3aalMsLBVzwRn5iJ3DUVIfYX9XXoIvqydtXtAJ+XocHrsQ6l4fl7Q2dYMq1X7gFF2+poZq+wE+ssQusH8OEMVpXtZyEippCfImMBrVzcBIkxaDAfUdYYXLHbxAI=
before_install:
- sudo apt-get update
- sudo apt-get install python python-pip
- sudo pip install couchapp
script:
- bundle exec middleman build --verbose
- cp -r build/* couchapp/_attachments
- ./scripts/deploy.sh
after_success:
- sudo pip install cloudant beautifulsoup4
- ./scripts/deploy-master.sh $USERNAME $PASSWORD
