rvm:
- 1.9.3
- 2.0.0
services:
- couchdb
env:
  global:
  - secure: Lx9uZVyAy7m7L2extALhhqEykVnGdE6FaHkHk58kGJVa/1vQoj3YTjtiPvt4kW+b4MnSpqrOBHEG853nXZv6ltnzRUloGAb0g7E6fLJEPCiBYNtXoEjHFmIOW48kuTCDXYGIUciX2KMTsexDcNbdPFy7iItT1M1MuLrdJA1vvuQ=
  - secure: UBDzqdJdfrsxqBnHuEesFXy06u0emSP8d6R14leK9fILVWHToTBro24jZxhCnCptjMIvve05kpsf+w0HHaOZjVLUfZW3kTVCIf6lTqknXI1zGiz2KTrkHRnLKq8y73vybK/ZRINebY8dqFwmtPAc1Sge6WrE/m38zmQUiNUa6MM=
before_install:
- sudo apt-get update
- sudo apt-get install python python-pip
- sudo pip install couchapp
script:
- bundle exec middleman build --verbose
- cp -r build/* couchapp/_attachments
- ./scripts/deploy.sh
after_success:
- sudo pip install cloudant beautifulsoup4
- ./scripts/deploy-master.sh $USERNAME $PASSWORD
