rvm:
- 1.9.3
- 2.0.0
services:
- couchdb
env:
  global:
  - secure: Lvi+mSpgVUbeiAbwKtNNlAUs82gmScx66ifsjTYIOhb3anw+Xl5lLbtFugiCDL5VYA+REeNrKyavCQdkrlmWYm9U65Z7vn/MWzPIyWjIkkFoeQJ6m4TcD7SawkbhQEF50tbHcXFlOcAQHKXL7v3bb3K+KLA+EC4D41D+wKV7Tfk=
  - secure: B0EVHgK/J2hz/RRMstIEgOath/K9u/M5XiPoqSm5N7x9QrDw4RhqIuVAxEHxnnz1cC4Jb3BV6PrheXAU3G0yEwbYVc+fP23ySxTlajriovhR1zv21BgMK8/TmBXIi8VmULjuBzH+9frg78ySbiSHFUWsLCp8zDwxAMfHxWltcbo=
before_install:
- sudo apt-get update
- sudo apt-get install python python-pip
- sudo pip install couchapp
script:
- bundle exec middleman build --verbose
- cp -r build/* couchapp/_attachments
- ./scripts/deploy.sh
after_success:
- sudo pip install cloudant beautifulsoup4
- ./scripts/deploy-master.sh $USERNAME $PASSWORD
