rvm:
- 1.9.3
- 2.0.0
services:
- couchdb
env:
  global:
  - secure: RVVXLdoAvl5XX5LRO27CmYZEcZ6pXhm78Pvd7SVsQqLL9++KIYPs966zdzrH2NHYVN3kvnOC1quBtPHE+LDzOLmDDRu0TyadtHBUolYFYN5zCoX3LFDj09be5ruZEaXLpnOLWSnXhqGVqidhxiM1B3C34jaxr0etMuVHbSpS9k4=
  - secure: RXSLp1t+j127T7Mk5OIb3WdaQ7MfBD/J5QkzHTWnbFG76mflYVSyT4HzSYaSY+OX9ajpZMmxNlDE/goNEV7iQ+/23TgD1UP8iqkDHKb+VIkUzG/Ep7AbepGcTXaVS/swgGylfEUtil+f5wpN1bpntDZ2MPl2Oxj6YbBONt8Ldzg=
before_install:
- sudo apt-get update
- sudo apt-get install python python-pip
- sudo pip install couchapp
script:
- bundle exec middleman build --verbose
- cp -r build/* couchapp/_attachments
- ./scripts/deploy.sh
after_success:
- sudo pip install cloudant beautifulsoup4
- ./scripts/deploy-master.sh $USERNAME $PASSWORD
